### ISSUE TITLE
CBS segmentation weight and depth

### ISSUE THREAD

**Issue by EmanuelGoncalves** [etal/cnvkit-examples#3]
Hi,

I'm trying to run the segmentation using CBS on a sample for which I do not have neither the weight or depth. According to DNAcopy documentation these are not required, although if I try to run:

`cnvkit.py segment data/test.foldchange.cnr -o data/test.foldchange.foldchange.cns`

I get:

`Error in weighted.mean.default(tbl$log2[start_bin:end_bin], tbl$weight[start_bin:end_bin]) : 
'x' and 'w' must have the same length
Calls: weighted.mean -> weighted.mean.default
Execution halted`

If I add two dummy columns filled with 1s for 'weight' and 'depth' the script seems to run well:

`Segmenting with method 'cbs', significance threshold 0.0001
Wrote data/A375_C902R2_P1D14.read_count.foldchange.cns with 160 regions`

My problem is that I don't understand what's being done behind the scenes with 'weight' and 'depth' and if this can affect my results.

Thank you in advance,

P.S: In the file formats docs it would be ideal to have an example file.

**Comment by etal** [comment]
How did you create/get test.foldchange.cnr?

I think you can automatically add the `depth` column with the script `cnn_updater.py`, included in the CNVkit distribution and otherwise available in the `scripts/` directory of the source tree. If that's not sufficient alone, then adding a `weight` of 1 to every bin should be fine.

The `weight` values do as you'd expect during segmentation, reducing the influence of less-reliable genomic regions on the segmentation result. If a pooled reference is used, the `fix` command calculates bin weights from the reference's `spread` and `log2` fields and puts the result in the .cnr output's `weight` column. I'll see about making the segmentation routines survive a missing `weight` column.

The `depth` column is optional, and not used in segmentation. It just shows the original read depth of each bin, before any normalization or other adjustments.

Example files are in the `test/formats/` directory of the source tree. I'll add links to some more of those files from the online docs.

**Comment by EmanuelGoncalves** [comment]
The test.foldchange.cnr was assembled manually and it's not an output of the CNVkit pipeline. It contains genomic regions and log2 ratios.

`cnn_updater.py` worked perfectly.

I'm new to all the CNV methodologies and I'm trying to repurposing these in a different context, so I didn't fully understand how the depth is automatically calculated, but I'll have a better look to the documentation.

Thank you for your time,

**Comment by EmanuelGoncalves** [comment]
Why does 'start' and 'end' is required for CbsModel (DNAcopy)? Their specification only requires the clones position.

Is it possible to use CNVkit CBS implementation with position only? I tried to set start and end to the same position but this does not work, I got the error below:

> Error in weighted.mean.default(tbl$log2[start_bin:end_bin], tbl$weight[start_bin:end_bin]) 

Thank you for your help,

**Comment by etal** [comment]
Try `end = start + 2` or so.

In CNVkit, the start and end positions are retained during segmentation to help debugging and troubleshooting, and simplify the conversion back to .cns format. To use DNAcopy or PSCBS directly on simulated data, you can just use either of those libraries in R without going through CNVkit first.

**Comment by EmanuelGoncalves** [comment]
Thank you, indeed that worked. Yes that might be best for me in this situation I was just trying to integrate too much R code with my python scripts.
